name: Metrics
on:
  # 每天 UTC 时间 0点 自动更新
  schedule: [{cron: "0 0 * * *"}]
  # 允许手动触发
  workflow_dispatch:
  # 当推送到主分支时触发 (可选)
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 在这里添加更多选项，例如：
          user: Hatedatastructures
          template: classic
          # base: header, activity, community, repositories, metadata
